---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: platform-secrets
  namespace: platform
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgChZJ8mlRBS92DVvcFT/BAC8n60EzQR09sG+f/xLxncx+F1GTfhqdhuD+QI5ohbmon1FePU508Unn65g2YYQTjyxmFHSXE0TFTJMQ22eQ0gUaGOv0V3NCwGK+4NZ8QXQwDuw69po7CfQC/7CtjD0dS5Oh6/6Px2zk8OGXzfe5dw7KTiVUvho9tdjFYWVdzTN53U5R5ycU87pBBap07MOyVLbXP+baPCTOHp52DOBCcdD0GBXvUDZIs9KREpuOHGzwi7Vt3l34YfvfVR/Fj67fTIaxy4Uq+xO12i1zJPI4OvXBU+nQ/hoDczdfuq1KW1CPvy99M3nzFUj/nbSd3BjNWLOr4285we1hd3o6+OXZDSCo6a3wQntC7GbKANq3BtnyZhD0DpywQI6OMMNfsmHTPIa04/wTE0BuquZWXxvsLO953FHeWMItQq9DY5/uHJtBDJhQXSuc/QxqtED+uiVP+49qWrmGWMVijABWmN4+oAZus2fTYVB8dslgSULlpwaAdroZkqEKkYI4yrA0LNMH49BC+pGp6zyWngt/tPFaDVqu1GYtKfBPCdcx84LmpaAEHl913NFuG+NuYBIf2jVb+LPQIBYOJtLJgnRD5aWynQd6rdrJWx7nHY63xHofdw/goTy5D40OyElXsiQ78WScwoKwxavvCAW8UAytvdGmev2BaH52Ry9Om9QLpxbxKWS67ZYiF0Q5b6S29ntrI=
    POSTGRES_PASSWORD: AgCAfXgk8dejtBGNkLXBHTEbQWCN7FXFuPv9HJsh8SluSta0rd5sxepvOU5a1JeLHdftu3ZSfynf6HXCZa2CaRQJwTdaovTZs7v2SmS+DVro6tY4W5oc1dR+wuuyaNTUKOQX/R5feLWws4NhXmJFJAxoEyz6f8b77wG4g/cCmAIzolcklaRgNYEL2gxfevfSWqpJ6hqglaKeumv+b4S8Oiy7SAC6iNEF/783pQZnqCkuMl632JfLBK+ieyuR2yUtoOHYMdXbSoQSBmoKQSvhBAN1Mk/TDd1q7aBjjI4o3IdwMKMPueCnTGjZ0zIqK1maKLQl1wNusIDIlyMzo7VYtBAzbFyMwbcuQA8QhZr9Gd2ORpe+rhyuECqhqZNrxKO0GzI4PhsYcIeBftsbJfHPdDeIEkiewPoz24rOCEj1B3hIkB8lE6anVFyMcoznGp86fxfVZH2a+6zGCZIimL6a+6ZScpG8u+IKEzi/AyPwYGYYhddL0iVjgLMq55+hTQWQL+SzOUWAzPIHQbkxlJRYgF5QOOHBWeDP5QEwfZKCEbzouDCh9I2Opp9y/xdpr1DTtcUWEIo1zPAzLi2ck6xrkJ7gy6amTaOVqYD+gWDLvNQrlPGb9Wt3uxxeh739ZGeVDRT0QEKnbkTOZPFTY1xGutGlNQTXPYenjWz56KFmxRD/5R101HJGHKQrCXiQteen+uUXIi4DpJlqhy0+7QeZ
  template:
    metadata:
      creationTimestamp: null
      name: platform-secrets
      namespace: platform
