apiVersion: v1
kind: Service
metadata:
  name: deadline-inference-staging
  namespace: ml
spec:
  selector:
    app: deadline-inference-staging
  ports:
    - name: http
      port: 8001
      targetPort: 8001
