apiVersion: v1
kind: Service
metadata:
  name: deadline-onnx-serving-canary
  namespace: ml
spec:
  selector:
    app: deadline-onnx-serving-canary
  ports:
    - name: http
      port: 8004
      targetPort: 8004
