apiVersion: apps/v1
kind: Deployment
metadata:
  name: deadline-inference-canary
  namespace: ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deadline-inference-canary
      release_channel: canary
  template:
    metadata:
      labels:
        app: deadline-inference-canary
        release_channel: canary
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: /metrics
    spec:
      containers:
        - name: deadline-inference-canary
          image: ghcr.io/bhanuu01/datanauts-inference-runtime:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: CLF_MODEL_PATH
              value: /models/classifier
            - name: NER_MODEL_PATH
              value: /models/ner
            - name: CONFIDENCE_THRESHOLD
              value: "0.7"
            - name: ONLINE_FEATURES_URL
              value: http://online-features.ml.svc.cluster.local:8000/ingest
            - name: PREDICTION_LOG_PATH
              value: /data/inference_predictions_canary.jsonl
            - name: RELEASE_CHANNEL
              value: canary
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          volumeMounts:
            - name: model-storage
              mountPath: /models
            - name: prediction-storage
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 20
            periodSeconds: 15
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: model-storage-pvc
        - name: prediction-storage
          persistentVolumeClaim:
            claimName: model-storage-pvc
