resources:
  - release-promotion-rbac.yaml
  - inference-staging-deployment.yaml
  - inference-staging-service.yaml
  - inference-canary-deployment.yaml
  - inference-canary-service.yaml
  - inference-production-deployment.yaml
  - inference-production-service.yaml
  - release-promotion-cronjob.yaml
