apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: datanauts-durable
  volumeName: paperless-postgres-pv
  resources:
    requests:
      storage: 10Gi
