apiVersion: v1
kind: Secret
metadata:
  name: chameleon-credentials
  namespace: ml
type: Opaque
stringData:
  OS_APPLICATION_CREDENTIAL_ID: "75ce894f8ece4c5e8c94dfa5956cb6fc"
  OS_APPLICATION_CREDENTIAL_SECRET: "hu74ZUq3xu__oy8CMO8LmxSCWUQubPhc7VzereMR23oVhS7G_GyemL7T9xiK93MVUr2EgP81ui_p4KMx5HCBDQ"
