apiVersion: v1
kind: Secret
metadata:
  name: chameleon-credentials
  namespace: ml
type: Opaque
stringData:
  OS_APPLICATION_CREDENTIAL_ID: "replace-with-your-chameleon-app-credential-id"
  OS_APPLICATION_CREDENTIAL_SECRET: "replace-with-your-chameleon-app-credential-secret"
