apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-quality-checks
  namespace: ml
spec:
  schedule: "30 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: data-quality-checks
              image: ghcr.io/bhanuu01/datanauts-data-monitoring:latest
              imagePullPolicy: IfNotPresent
              command: ["python", "ingestion_quality_check.py"]
              resources:
                requests:
                  cpu: "250m"
                  memory: "512Mi"
                limits:
                  cpu: "1000m"
                  memory: "1Gi"
