apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage-pvc
  namespace: ml
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: datanauts-durable
  volumeName: ml-model-storage-pv
  resources:
    requests:
      storage: 20Gi
