apiVersion: v1
kind: Service
metadata:
  name: online-features
  namespace: ml
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: /metrics
spec:
  selector:
    app: online-features
  ports:
    - name: http
      port: 8000
      targetPort: 8000
