apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-features
  namespace: ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: online-features
  template:
    metadata:
      labels:
        app: online-features
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8000"
    spec:
      nodeSelector:
        datanauts.io/durable-node: "true"
      containers:
        - name: online-features
          image: ghcr.io/bhanuu01/datanauts-online-features:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis.paperless.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: RUNTIME_DATA_S3_ENDPOINT_URL
              value: http://minio.platform.svc.cluster.local:9000
            - name: RUNTIME_DATA_BUCKET
              value: datanauts-runtime
            - name: AWS_ACCESS_KEY_ID
              value: mlflow
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secrets

                  key: MINIO_ROOT_PASSWORD
            - name: CHAMELEON_BUCKET
              value: "object_storage_proj11"
            - name: OS_AUTH_URL
              value: "https://chi.tacc.chameleoncloud.org:5000/v3"
            - name: OS_APPLICATION_CREDENTIAL_ID
              valueFrom:
                secretKeyRef:
                  name: chameleon-credentials
                  key: OS_APPLICATION_CREDENTIAL_ID
            - name: OS_APPLICATION_CREDENTIAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: chameleon-credentials
                  key: OS_APPLICATION_CREDENTIAL_SECRET
            - name: PRODUCTION_DATA_LOG_PATH
              value: /data/production_ingest.jsonl
            - name: FEEDBACK_LOG_PATH
              value: /data/feedback_events.jsonl
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          volumeMounts:
            - name: feedback-storage
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: feedback-storage
          persistentVolumeClaim:
            claimName: model-storage-pvc
