apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
  namespace: platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: datanauts-durable
  volumeName: platform-mlflow-pv
  resources:
    requests:
      storage: 10Gi
